### ISSUE TITLE
objOf function

### ISSUE THREAD

**Issue by HeilTec** [chrokh/fp-games#1]
I just watched your first episode on this and liked it. 
Then I liked to take a closer look at the code.

https://github.com/chrokh/snake/blob/8aee671823904b0b948f90051b381af7efaa0450/base.js#L10

When I see this I wonder if I missed a reason why not to use literal object construction:

``` javascript
const objOf     = k => v => ({ [k]: v })
```

**Comment by HeilTec** [comment]
Hey. Thanks for your response.

I was debating the implementation of `objOf` rather than using it or not.
It is indeed a useful function.

Taking a look at ramda reveals that your function is the same. [ramda](https://github.com/ramda/ramda/blob/master/source/objOf.js#L25-L27)

Wondering why not to use the shorter version led to this simple bench:

``` javascript
const objOf0 = k => v => ({[k]: v})
const objOf1 = k => v => { var o = {}; o[k] = v; return o }

const count = 1000000

const Start0 = new Date()
for (var i = 0; i < count; i++) { var o0 = objOf1(i)(i) }

const Start1 = new Date()
for (i = 0; i < count; i++) { var o1 = objOf0(i)(i) }

const finish = new Date()
console.log(Start1 - Start0) // 475
console.log(finish - Start1) // 735

```
Clearly ramda does it the faster way, but still - why is that the faster solution?

**Comment by chrokh** [comment]
Aha! I was simply not aware that this syntax existed!

Not sure why I didn't manage to read your initial post properly :disappointed: I see now that you clearly propose using computed property names, so I should have understood it the first time :smile: Apologies!

Changing to literal syntax with computed property names, reopening and closing :+1:
