### ISSUE TITLE
Poor question

### ISSUE THREAD

**Issue by Clingonboy** [chrokh/fp-games#6]
I'm trying to study your code, it is an ispiration for me.
I have a question, which is the difference between these three function?

`const rnd = min => max => Math.floor(Math.random() * max) + min;`

`const rnd2 =  (min, max) => { Math.floor(Math.random() * max) + min; }`

`function rnd3 (min, max) { return Math.floor(Math.random() * max) + min;}`

Why you use the first one?
I try all three and they seem to have the same behavior.
I have looking for some explination but I don't understand.
I'm very nubie :(

**Comment by chrokh** [comment]
Thanks for the question. I truly apologize for not having the time to answer this properly but here are some resources.

To understand the difference between `rnd` and `rnd2` you should learn about the concept of "currying" and why "partial application" is a very powerful tool in functional programming. Here are some quick links:
- https://blog.bitsrc.io/understanding-currying-in-javascript-ceb2188c339
- https://stackoverflow.com/questions/218025/what-is-the-difference-between-currying-and-partial-application
- https://en.wikipedia.org/wiki/Partial_application
- https://en.wikipedia.org/wiki/Currying

To understand the difference between `rnd2` and `rnd3` you should learn about the "arrow syntax" of JavaScript. Here are some quick links:

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions
- https://www.freecodecamp.org/news/when-and-why-you-should-use-es6-arrow-functions-and-when-you-shouldnt-3d851d7f0b26/

You should also be able to find a lot of stuff on YouTube. The three things to understand are "currying", "partial application", and "arrow functions". The first two are very general concepts in functional programming (or perhaps rather mathematics) and the third thing is specific to JavaScript.

Ps. I have not read the links (except Wikipedia) above myself so I apologize if they are not clear. But hopefully you now have the correct keywords.

I would also suggest checking out the following content from my YouTube channel:
- [An introduction to Ramda JS](https://www.youtube.com/watch?v=AINnOyUVEyI)
- [Playlist on Ramda JS](https://www.youtube.com/playlist?list=PLrhzvIcii6GMeyUfpn-o5xVCH3_UykrzI)
- [An introduction to Reason ML](https://www.youtube.com/watch?v=qZo-VWjC7es)


Best of luck in your studies! :)

**Comment by AntonStrand** [comment]
Even though I recommend you to take a look at the links above, the short answer is that `rnd` and `rnd2`is used differently. `rnd(10)(20)` vs `rnd2(10, 20)`.

`rnd` takes a number and returns a new function that takes a number and then returns a random value.
`rnd2` takes two numbers and returns a random value. It could be defined as `const rnd2 = (min, max) => rnd(min)(max)`.

Currying and partial application might seem weird at first but it is super useful to reduce code duplication and increase readability.
